name: Main workflow

on:
  push:

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    env:
      SECRET_ONE: ${{ secrets.SECRET_ONE }}
      SECRET_TWO: ${{ secrets.SECRET_TWO }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.7.12'

      - name: Check secrets available
        run: |
          echo $SECRET_ONE
          echo $SECRET_TWO
